name: Deployment
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn install
      - run: yarn build
      - run: GIT_USER=actions-user DEPLOYMENT_BRANCH=gh-pages yarn deploy
